### ISSUE TITLE
Mobile mode not working

### ISSUE THREAD

**Issue by tkohr** [geosolutions-it/MapStoreExtension#6] opened 2021-03-26 15:00 UTC
Hi,

we would like to develop en extension where the use case is "mobile first".

However, we encounter some problems when switching to a mobile view in chromium (89.0.4389.90) and firefox (87.0) dev tool and the app crashes.

![mapstore_mobile](https://user-images.githubusercontent.com/6329425/112650978-3bfc9600-8e4c-11eb-95ad-d9bf41454e46.png)

The error messages point to the `MapPlugin`:

```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MapPlugin`.

---

react-dom.development.js:26580 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MapPlugin`.

---

react_devtools_backend.js:2430 Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MapPlugin`.
```

Can be reproduced by switching to mobile mode on current master.

Any ideas on this would be great. Thanks!

**Comment by offtherailz** [comment] 2021-04-12 08:58
Thank you for reporting, this was caused by a missing migration of configuration. (see this https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#locate-plugin-configuration).
removing "tools": ["locate"] from localConfig.json solves the issue. The fix has been applied in PR #8

**Closed** 2021-04-12 09:05 UTC
